version: 2.1

workflows:
  version: 2
  build_and_deploy_workflow:
    jobs:
      build_and_deploy_job:
        filters:
          branches:
            only:
              -master



jobs:
  build_and_deploy_job:
    docker:
      -image: busybox

    steps:
      -run:
        name: hello world
        command: |
          echo "Hello world!!"